In [1]:
from bs4 import BeautifulSoup 
import requests
import smtplib
import time
import datetime
from datetime import datetime
import pandas as pd 
import csv

In [2]:
# connet to website 

Url='https://altin.in/'

head={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"}


page= requests.get(Url,headers=head)       

Soup1=BeautifulSoup(page.content,"html.parser")

Soup2=BeautifulSoup(Soup1.prettify(),"html.parser")


dolar=Soup2.find(id="dfiy").get_text()
dolar=dolar.strip()

euro=Soup2.find(id="efiy").get_text()
euro=euro.strip()

sterlin=Soup2.find(id="sfiy").get_text()
sterlin=sterlin.strip()


now = datetime.now()
dt_now = now.strftime("%d/%m/%Y %H:%M:%S")

print('1 $ =',dolar,'₺')

print('1 € =',euro,'₺')

print('1 £ =',sterlin,'₺')

1 $ = 13.4254 ₺
1 € = 15.1728 ₺
1 £ = 18.0933 ₺

In [3]:
header = ['Dolar', 'Euro','Sterlin','Date']
data = [dolar, euro,sterlin, dt_now]


with open('AltıninScraperDataset.csv', 'w', newline='', encoding='UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerow(data)

In [4]:
#Combine all of the above code into one function

def check_price():
    
    Url='https://altin.in/'

    head={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"}

    page= requests.get(Url,headers=head)       

    Soup1=BeautifulSoup(page.content,"html.parser")

    Soup2=BeautifulSoup(Soup1.prettify(),"html.parser")

   
    dolar=Soup2.find(id="dfiy").get_text()
    dolar=dolar.strip()

    euro=Soup2.find(id="efiy").get_text()
    euro=euro.strip()

    sterlin=Soup2.find(id="sfiy").get_text()
    sterlin=sterlin.strip()

    now = datetime.now()
    dt_now = now.strftime("%d/%m/%Y %H:%M:%S")
       
    data = [dolar, euro,sterlin, dt_now]

    with open('AltıninScraperDataset.csv', 'a+', newline='', encoding='UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(data)

In [5]:
i=1
while(i<25):
    check_price()
    time.sleep(1)
    i+=1

In [6]:
df = pd.read_csv('AltıninScraperDataset.csv')
df

      Dolar     Euro  Sterlin                 Date
0   13.4254  15.1728  18.0933  24/01/2022 17:17:43
1   13.4254  15.1728  18.0933  24/01/2022 17:17:44
2   13.4254  15.1728  18.0933  24/01/2022 17:17:45
3   13.4254  15.1728  18.0933  24/01/2022 17:17:46
4   13.4254  15.1728  18.0933  24/01/2022 17:17:48
5   13.4254  15.1728  18.0933  24/01/2022 17:17:49
6   13.4254  15.1728  18.0933  24/01/2022 17:17:50
7   13.4254  15.1728  18.0933  24/01/2022 17:17:52
8   13.4254  15.1752  18.0940  24/01/2022 17:17:53
9   13.4254  15.1752  18.0940  24/01/2022 17:17:55
10  13.4254  15.1751  18.0941  24/01/2022 17:17:56
11  13.4254  15.1751  18.0943  24/01/2022 17:17:57
12  13.4254  15.1751  18.0943  24/01/2022 17:17:59
13  13.4254  15.1751  18.0942  24/01/2022 17:18:00
14  13.4254  15.1751  18.0942  24/01/2022 17:18:01
15  13.4254  15.1751  18.0942  24/01/2022 17:18:03
16  13.4254  15.1751  18.0942  24/01/2022 17:18:04
17  13.4254  15.1751  18.0942  24/01/2022 17:18:06
18  13.4254  15.1751  18.0942  24/01/2022 17:18:07
19  13.4254  15.1751  18.0942  24/01/2022 17:18:08
20  13.4254  15.1751  18.0942  24/01/2022 17:18:10
21  13.4254  15.1751  18.0942  24/01/2022 17:18:11
22  13.4254  15.1751  18.0942  24/01/2022 17:18:12
23  13.4254  15.1751  18.0942  24/01/2022 17:18:14
24  13.4254  15.1751  18.0942  24/01/2022 17:18:15